config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :docs
  get 'welcome/index'
  
  authenticated :user do
    root 'docs#index', as: 'authenticated_root'
  end
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :set_doc, only: [:show, :edit, :update, :destroy]

  # GET /docs
  # GET /docs.json
  def index
    @docs = Doc.where(user_id: current_user)
  end

  # GET /docs/1
  # GET /docs/1.json
  def show
  end

  # GET /docs/new
  def new
    @doc = current_user.docs.build
  end

  # GET /docs/1/edit
  def edit
  end

  # POST /docs
  # POST /docs.json
  def create
    @doc = current_user.docs.build(doc_params)

    respond_to do |format|
      if @doc.save
        format.html { redirect_to @doc, notice: 'Doc was successfully created.' }
        format.json { render :show, status: :created, location: @doc }
      else
        format.html { render :new }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docs/1
  # PATCH/PUT /docs/1.json
  def update
    respond_to do |format|
      if @doc.update(doc_params)
        format.html { redirect_to @doc, notice: 'Doc was successfully updated.' }
        format.json { render :show, status: :ok, location: @doc }
      else
        format.html { render :edit }
        format.json { render json: @doc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docs/1
  # DELETE /docs/1.json
  def destroy
    @doc.destroy
    respond_to do |format|
      format.html { redirect_to docs_url, notice: 'Doc was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doc
      @doc = Doc.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doc_params
      params.require(:doc).permit(:title, :content)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.erb
<%= form_with(model: doc, local: true) do |form| %>
  <% if doc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doc.errors.count, "error") %> prohibited this doc from being saved:</h2>

      <ul>
      <% doc.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit class: "button" %>
  </div>
<% end %>

app/views/docs/edit.html.erb
<div class="wrapper_with_padding">
  <h1>Fix Doc</h1>

  <%= render 'form', doc: @doc %>
</div>

app/views/docs/index.html.erb
<div class="wrapper_with_padding">
  <div id="docs" class="clearfix">
    <% unless @docs.blank? %>
      <% @docs.each do |doc| %>
        <%= link_to url_for(doc) do %>
          <div class="doc">
            <p class="title"> <%= doc.title %> </p>
            <p class="date"> <%= time_ago_in_words(doc.created_at) %> </p>
            <p class="content"> <%= truncate(doc.content, length: 50) %> </p>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <h2>Create Doc!</h2>
      <button>
        <%= link_to 'Create Doc', new_doc_path %>
      </button>
    <% end %>
  </div>
</div>

app/views/docs/new.html.erb
<div class="wrapper_with_padding">
  <h1>New Doc</h1>

  <%= render 'form', doc: @doc %>
</div>

app/views/docs/show.html.erb
<div class="wrapper_with_padding">
  <div id="doc_show">
    <h1 class="title"> <%= @doc.title %> </h1>
    <p> <%= simple_format(@doc.content) %> </p>

    <div class="buttons">
      <%= link_to 'Fix Doc', edit_doc_path(@doc), class: "button" %>
      <%= link_to "Trash It", docs_path(@doc), method: :delete, data: { confirm: "Are you sure?" }, class: "button" %>
      <%= link_to 'Back', docs_path, class: "button" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FileCabinet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>  

    <header>
      <div class="header_inner">
        <%= link_to "FileCabinet", root_path, id: "logo" %>
      
        <nav>
          <% if user_signed_in? %>
            <%= link_to "Create Doc", new_doc_path %>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Log In", new_user_session_path %>
          <% end %>
        </nav>
      </div>
    </header>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div id="banner">
  <div class="banner_content">
    <h1>FileCabinet</h1>
    <p>Your life's work. Organized, always.</p>
    <button>
      <%= link_to "Enter", new_user_registration_path %>
    </button>
  </div>
</div>

<div id="callouts">
  <div class="callout_inner">
    <div class="wrapper">
      <div class="callout">
        <h2>Organize</h2>
        <p>Lorem ipsum dolor amet microdosing DIY leggings everyday carry master cleanse la croix helvetica iPhone tofu art party kogi cardigan. 
        Lumbersexual hexagon listicle fashion axe asymmetrical narwhal helvetica messenger bag succulents snackwave single-origin coffee. 
        Celiac post-ironic cold-pressed thundercats microdosing farm-to-table slow-carb bitters helvetica jean shorts. 
        Shaman food truck irony cronut kitsch. Raclette locavore fingerstache, vexillologist wolf enamel pin 90's keffiyeh farm-to-table butcher beard. 
        Intelligentsia ramps ethical chicharrones mixtape hoodie viral farm-to-table cliche literally semiotics pabst bespoke pinterest. 
        Tofu hoodie whatever tattooed try-hard intelligentsia vexillologist chambray yr raw denim.</p>
      </div>
    </div>
  </div>
</div>

<div id="bottom_cta">
  <div class="wrapper">
    <h2>Go Ahead!</h2>
    <br>
    <button>
      <%= link_to "Join Now", new_user_registration_path %>
    </button>
  </div>
</div>